import React from "react";
import type { Metadata } from "next";

import { Provider as ChakraProvider } from "@utils/libs/chakra-ui/providers";
import favicon from "./favicon.ico";
import GlobalLayout from "./layout/Global";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Notes APP with Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href={favicon.src} type="image/x-icon" />
      </head>
      <body>
        <ChakraProvider>
          <GlobalLayout>{children}</GlobalLayout>
        </ChakraProvider>
      </body>
    </html>
  );
}
